### ISSUE TITLE
询问框架架构的一些问题

### ISSUE THREAD

**Issue by Birger0** [youngfly/ARSD#1]
请问哪些代码对应了论文中的SSRD和MCFI模块呢？之前没用过基于mmdetection的目标检测。。。没看出来哪一部分在说明知识蒸馏，是增加了一个tea_pretrained参数么？

**Comment by youngfly** [comment]
https://github.com/youngfly/Remote-Sensing-Distillation/blob/master/mmdet/models/detectors/distill_atss.py
蒸馏的框架在这个里面，里面有两个模块和具体的注释
